buildpack: python_buildpack
memory: 1G
disk_quota: 2G
instances: 1
services:
# cf create-service postgres shared datagovau-dev-db
- datagovau-dev-db
# cf create-service redis32 standard datagovau-dev-redis
- datagovau-dev-redis
applications:
- name: datagovau-dev
